DROP TABLE Member CASCADE CONSTRAINTS;

CREATE TABLE Member(
    ID VARCHAR2(20), 
    PW             VARCHAR2(20)    NOT NULL, 
    Mileage        NUMBER          NOT NULL, 
    Nickname       VARCHAR2(20)    NOT NULL, 
    Premium        NUMBER          NOT NULL, 
    Country        VARCHAR2(20)    NOT NULL, 
    Share_Agree    VARCHAR2(20)    NOT NULL, 
    CONSTRAINT Member_ID_PK PRIMARY KEY(ID)
);

SELECT * from Member;

CREATE TABLE DANCE_INFO(
	SONG_TITLE		VARCHAR2(20),
	SONG_SINGER		VARCHAR2(20),
	SONG_FILEPATH	VARCHAR2(20)	NOT NULL,
	SONG_PRICE		NUMBER			NOT NULL,
	ALBUM_FILE_NAME VARCHAR2(20)	NOT NULL, 
	ALBUM_NAME		VARCHAR2(20)	NOT NULL,
	RELEASE_DATE	VARCHAR2(20)	NOT NULL,
	SONG_SEQ		INT,
	CONSTRAINT DENCE_INFO_PK PRIMARY KEY(SONG_SEQ)
);
SELECT * from DANCE_INFO;
INSERT INTO DANCE_INFO VALUES(
	'Butter', 'BT
S', './music/', '6', 'Butter', 'Butter', '2021-08-06', 6
)

CREATE TABLE EMBLEM_INFO(
	EMBLEM_FILE_NAME	VARCHAR2(20)	NOT NULL,
	EMBLEM_NAME			VARCHAR2(20)	NOT NULL
);
INSERT INTO EMBLEM_INFO VALUES(
'./emblem/' , '엠블럼1')
INSERT INTO EMBLEM_INFO VALUES(
'./emblem/' , '엠블럼2')
INSERT INTO EMBLEM_INFO VALUES(
'./emblem/' , '엠블럼3')

CREATE TABLE EMBLEM(
	ID	VARCHAR2(20),
	EMBLEM_NAME	VARCHAR2(20) NOT NULL,
	CONSTRAINT A FOREIGN KEY(ID) references MEMBER(ID),
	CONSTRAINT B FOREIGN KEY(EMBLEM_NAME) references EMBLEM_INFO(EMBLEM_NAME)
	);
	
drop table USER_DANCE_INFO;
CREATE TABLE USER_DANCE_INFO(
	PLAY_SEQ		NUMBER,
	ID				VARCHAR2(20),
	PREMIUM			VARCHAR2(20),
	PALY_DATE 		DATE, 
	SONG_TITLE		VARCHAR2(20),
	SONG_SINGER		VARCHAR2(20),
	ACCURACY		NUMBER,
	USER_FILE_NAME	VARCHAR2(20),
	SEASON			VARCHAR2(20),
	ARTICLE_SEQ		NUMBER,
	SONG_SEQ		NUMBER,
	CONSTRAINT A	PRIMARY KEY (PLAY_SEQ),
	CONSTRAINT B	FOREIGN KEY(ID) references Member(ID),
	CONSTRAINT C	FOREIGN KEY(SONG_SEQ) references DANCE_INFO(SONG_SEQ)
);

DROP TABLE USER_DANCE_INFO CASCADE CONSTRAINTS;